////////////////////////////////////////////////////////////////////////////////
///
/// effectsListTests.cpp
/// --------------------
///
///   The effect tables are no longer generated by CMake, so their internal
/// consistency is now something a test has to assert rather than something the
/// generator guaranteed by construction. Index order is ABI: presets and host
/// automation refer to effects by index.
///
/// Copyright (c) 2026 the SpectrumWorx contributors.
/// SPDX-License-Identifier: GPL-3.0-or-later
///
////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
#include "le/spectrumworx/effects/configuration/constants.hpp"
#include "le/spectrumworx/effects/configuration/effectNames.hpp"
#include "le/spectrumworx/effects/configuration/effectsList.hpp"
#include "le/spectrumworx/effects/configuration/includedEffects.hpp"
#include "le/spectrumworx/effects/configuration/indexToEffectImplMapping.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <cstdint>
#include <set>
#include <string_view>
#include <type_traits>
#include <vector>
//------------------------------------------------------------------------------

namespace Effects = LE::SW::Effects;

namespace
{
#define LE_SW_AUX_COUNT(folder, module, name) +1
constexpr unsigned int listedEffects{0 LE_SW_EFFECT_LIST(LE_SW_AUX_COUNT)};
#undef LE_SW_AUX_COUNT

std::vector<std::string_view> effectNames()
{
    std::vector<std::string_view> names;
    for (std::uint8_t index(0); index < Effects::Constants::numberOfEffects; ++index)
        names.emplace_back(Effects::effectName(index));
    return names;
}
} // anonymous namespace

TEST_CASE("The list and the counts agree", "[effects]")
{
    static_assert(listedEffects == Effects::Constants::numberOfEffects);
    static_assert(Effects::Constants::numberOfEffects == 57);
    static_assert(Effects::Constants::numberOfIncludedEffects ==
                  Effects::Constants::numberOfEffects);
}

TEST_CASE("Every effect ships now that editions are gone", "[effects]")
{
    static_assert(Effects::includedEffects.size() == Effects::Constants::numberOfEffects);
    CHECK(std::all_of(Effects::includedEffects.begin(), Effects::includedEffects.end(),
                      [](bool const included) { return included; }));
}

TEST_CASE("ValidIndices covers every effect", "[effects]")
{
    // Utility::switchOn and Utility::forEach dispatch over this. It used to be
    // a boost::mpl::range_c walked by a Boost.Preprocessor-generated switch,
    // whose BOOST_SWITCH_LIMIT had to grow past 50 to accommodate it.
    static_assert(Effects::ValidIndices::size == Effects::Constants::numberOfEffects);
}

TEST_CASE("Every index maps to a distinct implementation type", "[effects]")
{
    // std::tuple_element over EffectImpls replaced 57 explicit template
    // specialisations written by CMake; a duplicate would silently make two
    // effects the same effect.
    static_assert(std::tuple_size_v<Effects::EffectImpls> ==
                  Effects::Constants::numberOfEffects + 1);
    static_assert(std::is_same_v<Effects::ImplForIndex<0>::type,
                                 std::tuple_element_t<0, Effects::EffectImpls>>);
    static_assert(!std::is_same_v<Effects::ImplForIndex<0>::type, Effects::ImplForIndex<1>::type>);
    static_assert(
        std::is_same_v<Effects::ImplForIndex<Effects::Constants::numberOfEffects>::type, void>);
}

/// \note Nothing here checks which group an effect is in: that is a menu
/// question, answered in gui/editor/moduleMenuLayout.cpp so that the answer can
/// also say what *order* the groups come in, and held by
/// `tests/gui/moduleMenuTests.cpp`.

TEST_CASE("Effect names are present and unique", "[effects]")
{
    auto const names(effectNames());
    REQUIRE(names.size() == Effects::Constants::numberOfEffects);
    for (auto const &name : names)
    {
        CHECK_FALSE(name.empty());
    }
    std::set<std::string_view> const unique(names.begin(), names.end());
    CHECK(unique.size() == names.size());
}

TEST_CASE("effectIndex is the inverse of effectName", "[effects]")
{
    for (std::uint8_t index(0); index < Effects::Constants::numberOfEffects; ++index)
        CHECK(Effects::effectIndex(Effects::effectName(index)) == static_cast<std::int8_t>(index));

    CHECK(Effects::effectIndex("no such effect") == -1);
}

TEST_CASE("The index order presets depend on has not moved", "[effects]")
{
    // Appending is allowed; reordering or removing breaks every saved preset
    // and every host automation assignment in the wild.
    auto const names(effectNames());
    CHECK(names.front() == std::string_view(Effects::PitchShifter::title));
    CHECK(names.back() == std::string_view(Effects::Quantizer::title));
    // Timbre starts at 7, after Pitch's seven.
    CHECK(names[7] == std::string_view(Effects::Bandpass::title));
    CHECK(names[8] == std::string_view(Effects::Bandstop::title));
}
